package healthlet;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;


public class NewJFrame2 extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame2
     */
    public NewJFrame2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jt1 = new javax.swing.JTextField();
        jt2 = new javax.swing.JTextField();
        jt3 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        admit_date = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Record Addition Window");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Enter Patient's Name");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 81, 149, 23));

        jLabel2.setText("Enter Patient Number ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 39, 149, 24));

        jLabel3.setText("Enter Patient's Ailment");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 126, 149, 24));

        jt1.setToolTipText("Enter number like 1,2,3,...");
        getContentPane().add(jt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 39, 119, 30));
        getContentPane().add(jt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 81, 119, 30));
        getContentPane().add(jt3, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 126, 119, 30));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app_icons/add-1-icon.png"))); // NOI18N
        jButton1.setText("Enter Patient Record in the database");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 273, 40));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app_icons/Close-2-icon.png"))); // NOI18N
        jButton2.setText("EXIT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 100, 40));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app_icons/Go-back-icon.png"))); // NOI18N
        jButton3.setText("BACK");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 270, 100, 40));

        jLabel5.setText("Enter admit date");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 110, -1));

        admit_date.setDateFormatString("dd-MM-yyyy");
        getContentPane().add(admit_date, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 170, 120, 30));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app_icons/Plus.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 320));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        String patient_name, patient_ailment;
        NewJFrame4 nj4 = new NewJFrame4();
        int patient_no = Integer.parseInt(jt1.getText());
        patient_name = nj4.title(jt2.getText());
        patient_ailment = nj4.title(jt3.getText());
        SimpleDateFormat Format = new SimpleDateFormat("dd-MM-yyyy");
        Date dobj = admit_date.getDate();
        String date = Format.format(dobj);
        //String date = DateIn.getText();
        
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:derby://localhost:1527/Apex Hospital","root","abc");
            Statement stmt = con.createStatement();
            String query = "INSERT INTO PATIENTS VALUES ("+patient_no+", '"+patient_name+"', '"
                    +patient_ailment+"', 'Admitted', '" + date + "', 'NA')";
            stmt.executeUpdate(query);
            stmt.close();
            con.close(); 
            JOptionPane.showMessageDialog(null, "Patient Added","Successfully Added", JOptionPane.PLAIN_MESSAGE);}
        
        catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Patient Number already added!", "Operation Unsuccessful", JOptionPane.ERROR_MESSAGE);
            //JOptionPane.showMessageDialog(null, e);
            try{
                Class.forName("com.mysql.cj.jdbc.Driver");
                Connection con = DriverManager.getConnection("jdbc:derby://localhost:1527/Apex Hospital","root","abc");
                Statement stmt = con.createStatement();
                String check = "SELECT * FROM PATIENTS";
                ResultSet rs = stmt.executeQuery(check);
                int maxm = 0;
                while (rs.next()){
                    int num = rs.getInt("PATIENT_NUMBER");
                    if (num > maxm){
                        maxm = num;
                    }
                }
                maxm ++;
                JOptionPane.showMessageDialog(null, "Try " + maxm + " as Patient number.", "Try", JOptionPane.PLAIN_MESSAGE);
            }
            catch(Exception exp){
                JOptionPane.showMessageDialog(null, exp);
            }

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
this.setVisible(false);
new NewJFrame1().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser admit_date;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jt1;
    private javax.swing.JTextField jt2;
    private javax.swing.JTextField jt3;
    // End of variables declaration//GEN-END:variables
}
