package healthlet;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author divyanshu
 */
public class NewJFrame3 extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame3
     */

    public NewJFrame3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jt1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        discharge_date = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Patient Discharge Window");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Lucida Console", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Enter Patient Number:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 200, 29));

        jt1.setToolTipText("Enter number like 1,2,3,...");
        jt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jt1ActionPerformed(evt);
            }
        });
        getContentPane().add(jt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, 120, 29));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app_icons/Analytics-icon.png"))); // NOI18N
        jButton1.setMnemonic('e');
        jButton1.setText("Discharge");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 113, 149, -1));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app_icons/Go-back-icon.png"))); // NOI18N
        jButton4.setMnemonic('B');
        jButton4.setText("BACK");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 110, -1));

        jLabel3.setFont(new java.awt.Font("Lucida Console", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Enter Discharge Date:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 190, 20));

        discharge_date.setDateFormatString("dd-MM-yyyy");
        getContentPane().add(discharge_date, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, 120, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app_icons/Plus.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 380, 240));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int patient_no = Integer.parseInt(jt1.getText());
        SimpleDateFormat Format = new SimpleDateFormat("dd-MM-yyyy");
        Date dobj = discharge_date.getDate();
        String dis_date = Format.format(dobj);
        
        try { 
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:derby://localhost:1527/Apex Hospital","root","abc");
            Statement stmt = con.createStatement();
            String check = "SELECT * FROM PATIENTS WHERE PATIENT_NUMBER = " + patient_no;
            ResultSet rs = stmt.executeQuery(check);
            if(rs.next()){
                String cur = rs.getString("STATUS");
                if (cur.equals("Discharged")){
                    JOptionPane.showMessageDialog(null, "Patient Already Discharged","Operation Unsuccessful ", JOptionPane.ERROR_MESSAGE);
                    jt1.setText("");
                }
                else{
                    String query = "UPDATE PATIENTS SET STATUS = 'Discharged', DISCHARGEDATE = '" + dis_date + "' WHERE PATIENT_NUMBER = " + patient_no + "";
                    stmt.executeUpdate(query);
                    JOptionPane.showMessageDialog(null, "Patient number "+patient_no+" can now be discharged","Discharge Successful", JOptionPane.PLAIN_MESSAGE);
                    
                    this.setVisible(false);
                    new NewJFrame5(dis_date, patient_no).setVisible(true);
                }
            }
            else{
                JOptionPane.showMessageDialog(null, "Patient Does Not Exist!","Operation Unsuccessful ", JOptionPane.ERROR_MESSAGE);
                jt1.setText("");
            }
            }
            
        
        catch (Exception e) {JOptionPane.showMessageDialog(null, e);}           // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        this.setVisible(false);
        new NewJFrame1().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jt1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser discharge_date;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jt1;
    // End of variables declaration//GEN-END:variables
}
