package healthlet;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author harsh
 */
public class NewJFrame4 extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame4
     */
    public String title(String mess){
        String res = "";
		boolean flag = true;
		for (int i = 0; i < mess.length(); i++) {
			if (flag == true) {
				res += Character.toString(mess.charAt(i)).toUpperCase();
				flag = false;
			}
			else {
				res += Character.toString(mess.charAt(i)).toLowerCase();
			}
			if (mess.charAt(i) == ' ') {
				//res += mess.charAt(i);
				flag = true;
			}
		}
		return res;
    }
    public NewJFrame4() {
        initComponents();
        DefaultTableModel tm = (DefaultTableModel)jtb1.getModel();
        try { Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:derby://localhost:1527/Apex Hospital","root","abc");
            Statement stmt = con.createStatement();
            String query = "SELECT * FROM PATIENTS";
            ResultSet rs = stmt.executeQuery(query);

            while (rs.next())
            { String a = rs.getString("PATIENT_NUMBER");
                String b = rs.getString("PATIENT_NAME");
                String c = rs.getString("PATIENT_AILMENT");
                String d = rs.getString("STATUS");
                String e = rs.getString("ADMITDATE");
                String f = rs.getString("DISCHARGEDATE");
                Object[] xy = {a, b, c, d, e, f};
                tm.addRow(xy);}
            rs.close();
            stmt.close();
            con.close();}

        catch (Exception e) {JOptionPane.showMessageDialog(null, e);}
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox1 = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtb1 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jt1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        jCheckBox1.setText("jCheckBox1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Record Viewing Window");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtb1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Patient_Number", "Patient_Name", "Patient_Ailment", "Status", "Admit Date", "Discharge Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jtb1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 580, 136));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app_icons/Close-2-icon.png"))); // NOI18N
        jButton2.setText("EXIT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 240, 95, 40));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app_icons/Go-back-icon.png"))); // NOI18N
        jButton4.setText("BACK");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 100, 40));

        jLabel1.setFont(new java.awt.Font("Lucida Console", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Enter Patient Name:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 187, 157, 21));
        getContentPane().add(jt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(264, 187, 205, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app_icons/AI.png"))); // NOI18N
        jButton1.setText("SEARCH");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, 120, 40));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app_icons/Data-Alphabetical-Sorting-Za-icon.png"))); // NOI18N
        jButton3.setText("SHOW ALL");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 240, 145, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app_icons/Plus.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -6, 600, 320));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        this.setVisible(false);
        new NewJFrame1().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        String name = jt1.getText();
        NewJFrame4 nj4 = new NewJFrame4();
        name = nj4.title(name);


DefaultTableModel tm = (DefaultTableModel)jtb1.getModel();
for (int i = tm.getRowCount() - 1; i >= 0; i-- ) 
    {tm.removeRow(i);}

        try { Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:derby://localhost:1527/Apex Hospital","root","abc");
            Statement stmt = con.createStatement();
            String query = "SELECT * FROM PATIENTS WHERE PATIENT_NAME = '"+name+"'";
            ResultSet rs = stmt.executeQuery(query);

            while (rs.next())
            { String a = rs.getString("PATIENT_NUMBER");
                String b = rs.getString("PATIENT_NAME");
                String c = rs.getString("PATIENT_AILMENT");
                String d = rs.getString("STATUS");
                String e = rs.getString("ADMITDATE");
                String f = rs.getString("DISCHARGEDATE");
                Object[] xy = {a, b, c, d, e, f};
                tm.addRow(xy);}
            rs.close();
            stmt.close();
            con.close();}

        catch (Exception e) {JOptionPane.showMessageDialog(null, e);}        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
DefaultTableModel tm = (DefaultTableModel)jtb1.getModel();
for (int i = tm.getRowCount() - 1; i >= 0; i-- ) 
    {tm.removeRow(i);}

        try { Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:derby://localhost:1527/Apex Hospital","root","abc");
            Statement stmt = con.createStatement();
            String query = "SELECT * FROM PATIENTS";
            ResultSet rs = stmt.executeQuery(query);

            while (rs.next())
            { String a = rs.getString("PATIENT_NUMBER");
                String b = rs.getString("PATIENT_NAME");
                String c = rs.getString("PATIENT_AILMENT");
                String d = rs.getString("STATUS");
                String e = rs.getString("ADMITDATE");
                String f = rs.getString("DISCHARGEDATE");
                Object[] xy = {a, b, c, d, e, f};
                tm.addRow(xy);}
            rs.close();
            stmt.close();
            con.close();}

        catch (Exception e) {JOptionPane.showMessageDialog(null, e);}        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jt1;
    public javax.swing.JTable jtb1;
    // End of variables declaration//GEN-END:variables
}
